### ISSUE TITLE
Membership Page & other long pages

### ISSUE THREAD

**Issue by HerinHentry** [mr-bobz/talarts#147]
http://talarts.knowbility.org/services/membership/

The pages are very long and hence hard for the cognitive impaired users (using pointer devices/left hand mouse/huff and puff) to scroll thru the entire page. Is it possible to fix internal anchors with in the page to go to each section & then to top?

@christosptr : What are your thoughts on this?

![image](https://cloud.githubusercontent.com/assets/15111528/11024884/d5df8596-86e8-11e5-9b5c-c28c5cf78893.png)

**Comment by christosptr** [comment]
Yes this is a good idea to add anchor tags to go to the top of the page at
the end of each section

Cheers Christos
Send from my mobile device

**Comment by mr-bobz** [comment]
Assigning back to you Herin as this could be done via WP itself, pls reassign to some one else in the team, tx

**Comment by christosptr** [comment]
I will take it

**Comment by anoopm7** [comment]
herin please have a look and advise, if any changes. once its reviewed i can apply to other pages.

**Comment by anoopm7** [comment]
http://talarts.knowbility.org/testing-page/#link3
http://talarts.knowbility.org/testing-page/

Please check and reassign.

**Comment by HerinHentry** [comment]
Thanks @anoopm7 . Please progress with what we discussed in slack. Will check tomorow.

**Comment by anoopm7** [comment]
http://talarts.knowbility.org/services/whatwedo/
http://talarts.knowbility.org/services/membership/

**Comment by christosptr** [comment]
@anoopm7 and @HerinHentry This looks good
but i think it would be useful if we add the role="region" and an aria-label="Document Navigation"
on the following div in order to give some more information to the screen reader users
Current HTML
<div class="siteorigin-widget-tinymce textwidget">
Suggested HTML
<div class="siteorigin-widget-tinymce textwidget" role="region"  aria-label="Document Navigation">

**Comment by HerinHentry** [comment]
Thanks @christosptr . Valid one.
@anoopm7 : This looks great. One other i identified was 
<...a href="#top">Move to top<.../a>
This link refers to anchor #top. But, there is no anchor set on membership page. Can you please look? What we do page has the anchor.

**Comment by anoopm7** [comment]
@HerinHentry Added the top anchor
@mr-bobz 
1. Is it ok to add the following css ? If yes, where?
ul.mbr{
white-space:normal;
padding-left:35px;
}
This css helps align and correct spacing in the link headers on memebrships and what we do page.

.2. role and aria-label tag mentioned above by chris :  Is this  injected during run time? If so, will you be able to add role and aria-label to it?

**Comment by anoopm7** [comment]
@mr-bobz - assigning you this for the two attributes mentioned by chris above.

**Comment by anoopm7** [comment]
herin has created 165 and i will switch to there.

**Comment by mr-bobz** [comment]
Added in the WP editor as well as via jQuery (custom.js)

![5dad9daa2819d9a0](https://cloud.githubusercontent.com/assets/12365601/11110843/689a20d0-8955-11e5-8231-b3ba436d0df5.jpg)

**Comment by mr-bobz** [comment]
I feel the page implementation is a bit odd. Instead of adding an empty div with id top, can't we just set the id for the heading and move to there? Else clicking on 'Move to top'  takes to nothing and could be confusing for user/screen reader.

Also instead of using div for above navigation list, I think ul-li would be better. Would look good too.

**Comment by anoopm7** [comment]
@mr-bobz  the empty div is because the user can see header when move to top is clicked. if you give the id to heading then when you click on move to top the header is actually not visible and needs to be scrolled. Please advise. 

With ul/li instead of divs, steve mentioned that single li lists should be avoided. I can check with herin if 1 ul with several li is fine to be used?

**Comment by anoopm7** [comment]
@HerinHentry

**Comment by mr-bobz** [comment]
Fixed

**Comment by HerinHentry** [comment]
Excellent! Closing now
